import smtplib

from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.headerregistry import Address
from email.utils import formatdate


def is_expired(timestamp, minutes):
    exptime = datetime.utcnow() - timedelta(minutes=minutes)
    expired = bool(timestamp < exptime)
    return expired


def email_recovery(username, address, token):
    message = (
        "Hey there!\n\n\tWe just received a request to reset "
        + "the Computer Science House account '{}'. According the information "
        + "we have about the account, this email ({}) is listed as an "
        + "alternative. If you requested this password reset, please click "
        + "the link below and proceed with the password reset. If not, please "
        + "contact an RTP immediately at rtp@csh.rit.edu. "
        + "\n\nhttps://account.csh.rit.edu/reset?token={}\n\n"
        + "This token is only valid for 30 minutes, after that you will need to "
        + "reverify your identity.\n\n"
        + "Thanks,\nRoot Type People\nComputer Science House\nrtp@csh.rit.edu"
        + "\n\nThis message was automatically generated by the CSH account "
        + "recovery utility."
    )

    message = message.format(username, address, token)

    email = MIMEText(message)
    email["To"] = address
    email["From"] = "CSH Account Recovery <rtp@csh.rit.edu>"
    email["Subject"] = "Your Requested Account Reset"
    email["Date"] = formatdate()

    server = smtplib.SMTP("mail.csh.rit.edu")
    server.send_message(email)
    server.quit()


def phone_recovery(phone, carrier, token):

    carrier_relay = {
        "alltel": "@text.wireless.alltel.com",
        "att": "@txt.att.net",
        "boost": "@myboostmobile.com",
        "cricket": "@sms.mycricket.com",
        "sprint": "@messaging.sprintpcs.com",
        "tmobile": "@tmomail.net",
        "us": "@email.uscc.net",
        "verizon": "@vtext.com",
        "virgin": "@vmobl.com",
    }

    address = phone + carrier_relay[carrier]

    message = "Your CSH account recovery PIN is: {}"

    message = message.format(token)

    email = MIMEText(message)
    email["To"] = address
    email["From"] = "rtp@csh.rit.edu"
    email["Date"] = formatdate()

    server = smtplib.SMTP("mail.csh.rit.edu")
    server.send_message(email)
    server.quit()
