"""
Funtions dealing with direct LDAP and FreeIPA communications.
"""

import re
import ldap as pyldap

from selfservice import app, ldap, ipa


def verif_methods(username):
    """
    Check LDAP for information about the provided user which could be used
    to verify their identity.

    Keyword arguments:
    username -- Username of account to lookup
    """
    methods = {"email": [], "phone": [], "rit": None}

    user = ldap.get_member(username, True)

    if user.mail:
        for addr in user.__getattr__("mail", as_list=True):
            if "rit.edu" not in addr and "@" in addr:
                name, domain = addr.strip().split("@")
                display = name[:1] + "..." + name[-1:] + "@" + domain
                methods["email"].append({"data": addr, "display": display})

    if user.mobile:
        for number in user.__getattr__("mobile", as_list=True):
            stripped = re.sub("[^0-9]", "", number)
            if len(stripped) == 10:
                display = "(XXX) XXX-{}".format(stripped[-4:])
                methods["phone"].append({"data": stripped, "display": display})

    if user.telephoneNumber:
        for number in user.__getattr__("telephoneNumber", as_list=True):
            stripped = re.sub("[^0-9]", "", number)
            if len(stripped) == 10:
                methods["phone"].append(stripped)

    if user.ritDn:
        methods["rit"] = user.ritDn.split(",")[0].replace("uid=", "")

    return methods


def get_members():
    """
    Get a list of all members in FreeIPA
    """
    members = []
    ldap_conn = ldap.get_con()
    res = ldap_conn.search_s(
        "cn=users,cn=accounts,dc=csh,dc=rit,dc=edu",
        pyldap.SCOPE_SUBTREE,
        "(uid=*)",
        ["uid", "displayName"],
    )
    for member in res:
        members.append(
            {
                "value": member[1]["uid"][0].decode("utf-8"),
                "display": member[1]
                .get("displayName", member[1]["uid"])[0]
                .decode("utf-8"),
            }
        )

    return members


def ipa_login():
    """
    Use IPA admin credentials and ensure object is authenticated.
    """
    username = app.config["LDAP_BIND_DN"].split(",")[0].split("=")[1]
    password = app.config["LDAP_BIND_PW"]
    ipa.login(username, password)


def create_ipa_otp(username, secret):
    """
    Create an OTP object in FreeIPA for the given user.

    Keyword arguments:
    username -- Username of account to use as object owner
    secret -- Secret generated by Keycloak
    """
    ipa_login()
    data = {"ipatokenowner": username, "ipatokenotpkey": secret}
    ipa._request("otptoken_add", params=data)


def delete_ipa_otp(username):
    """
    Remove all OTP tokens from the given user's account.

    Keyword arguments:
    username -- Username of account to lookup
    """
    ipa_login()
    token_info = ipa._request("otptoken_find", params={"ipatokenowner": username})
    for token in token_info["result"]:
        ipa._request("otptoken_del", args=[token["ipatokenuniqueid"][0]])
