"""empty message

Revision ID: 768bc2a00e10
Revises: 
Create Date: 2018-05-24 01:32:46.291969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768bc2a00e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_session',
    sa.Column('secret', sa.String(length=100), nullable=False),
    sa.Column('form', sa.Binary(), nullable=True),
    sa.Column('session', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('secret')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_codes',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('phone_codes')
    op.drop_table('session')
    op.drop_table('otp_session')
    # ### end Alembic commands ###
