"""change created to expires

Revision ID: 92c9d8ea5b74
Revises: fdb69cd98e19
Create Date: 2026-03-15 20:16:42.829689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92c9d8ea5b74'
down_revision = 'fdb69cd98e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('created', new_column_name='expires')

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('created', new_column_name='expires')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('expires', new_column_name='created')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('expires', new_column_name='created')

    # ### end Alembic commands ###
