"""empty message

Revision ID: a8f222f4fbdf
Revises: 
Create Date: 2018-05-19 02:56:01.689980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f222f4fbdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_codes',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('phone_codes')
    op.drop_table('session')
    # ### end Alembic commands ###
