"""empty message

Revision ID: d0cb830640a0
Revises: 
Create Date: 2018-05-22 14:47:33.391477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cb830640a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_codes',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('session', sa.String(length=36), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('phone_codes')
    op.drop_table('session')
    # ### end Alembic commands ###
