"""Add Sessions and Phone Reset

Revision ID: d97b8ffd16a0
Revises: b7ff6d540e59
Create Date: 2018-05-02 22:10:54.098818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97b8ffd16a0'
down_revision = 'b7ff6d540e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_codes',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('username', 'code')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('phone_codes')
    # ### end Alembic commands ###
